version: '3'

services:
  web:
    build: .
    command: gunicorn FoodTrucks.wsgi:application -b 0.0.0.0:8000
    expose:
      - "8000"
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
