# Generated by Django 5.0 on 2023-12-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodtruck", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="truck",
            name="address",
            field=models.CharField(default="Address", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="truck",
            name="description",
            field=models.TextField(default="Address"),
            preserve_default=False,
        ),
    ]
